Stringstream
UG-MSU/container-lib pull request #36
Opened 2023-02-13 20:54 UTC by CapybaraV

2023-03-13 21:29 UTC, ipsavitsky requested changes

2023-03-13 21:29 UTC, ipsavitsky commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-g")
это либо убрать, либо заменить на добавление флага только в Debug сборке

2023-03-13 21:29 UTC, ipsavitsky commented on .gitignore
> -.vscode/**
не очень понятно зачем убирать и соответственно лить свои конфиги в репозиторий. Есть конфиги - замечательно, пусть остаются у тебя. Нужна аргументация почему они должны быть в мастере

2023-03-13 21:29 UTC, ipsavitsky commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-g")
```suggestion
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -Wall -Wextra -pg")
```

2023-03-13 21:29 UTC, ipsavitsky commented on test.txt
> +/sys/fs/cgroup/yats/bebraa
что это и зачем это?

2023-03-13 21:49 UTC, ippishio commented on .gitignore
> -.vscode/**
аэээ удобно эээ

2023-03-13 21:50 UTC, ippishio commented on .gitignore
> -.vscode/**
кстати я у тебя спрашивал можно ли залить их или нет, ответ был положительный. но они все равно не рабочие, так что пофек

2023-03-13 21:51 UTC, ippishio commented on test.txt
> +/sys/fs/cgroup/yats/bebraa
случайно

2023-03-14 10:22 UTC, ipsavitsky approved these changes

2023-03-14 10:23 UTC, merged