added_shared_memory
UG-MSU/container-lib pull request #43
Opened 2023-03-24 14:38 UTC by PaRat07

2023-03-24 19:46 UTC, ipsavitsky requested changes

2023-03-24 19:46 UTC, ipsavitsky commented on src/container-lib.cpp
> +    auto *threads_amount = reinterpret_cast<size_t*>(mmap(nullptr, sizeof(size_t), PROT_READ | PROT_WRITE, MAP_SHARED, -1, 0));
Корежит меня от `auto` в этом моменте, особенно сразу после `reinterpret_cast`

2023-03-24 19:46 UTC, ipsavitsky commented on src/wrapper.cpp
неясно, почему больше нет этого параметра. Объяснить.

2023-03-24 20:15 UTC, PaRat07 commented on src/container-lib.cpp
> +    auto *threads_amount = reinterpret_cast<size_t*>(mmap(nullptr, sizeof(size_t), PROT_READ | PROT_WRITE, MAP_SHARED, -1, 0));
мне так Clang-Tidy сказал, чтобы тип не повторять

2023-03-24 20:16 UTC, PaRat07 commented on src/wrapper.cpp
я же храню это в threads_amount

2023-03-28 11:23 UTC, ipsavitsky commented on src/container-lib.cpp
> +    auto *threads_amount = reinterpret_cast<size_t*>(mmap(nullptr, sizeof(size_t), PROT_READ | PROT_WRITE, MAP_SHARED, -1, 0));
хорошо

2023-03-28 11:24 UTC, ipsavitsky requested changes

2023-03-28 11:24 UTC, ipsavitsky commented on src/wrapper.cpp
тогда почему он не добавлен?

2023-03-28 16:28 UTC, PaRat07 commented on src/wrapper.cpp
я храню в переменной в методе

2023-03-28 19:53 UTC, ipsavitsky approved these changes

2023-03-28 19:53 UTC, ipsavitsky commented on src/wrapper.cpp
все, наконец до меня доперло, что `forks_threshold` это другоая переменная. Так и надо.

2023-03-28 19:53 UTC, merged